### ISSUE TITLE
Invalid version

### ISSUE THREAD

**Issue by FurryApocalypse** [zhmed/koftafurnituremod#1]
Hi there.
I have problem with compatibility 1.19.2 
![image](https://github.com/zhmed/koftafurnituremod/assets/75454834/b47083b0-50e9-4ab7-ac63-bfe79cdc96e5)

There is range in description 1.19.2 to 1.19.4

Please fix if possible or change description.
Cheers :)

**Comment by zhmed** [comment]
ill fix with the next update
